on: [ push, pull_request ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - run: gradle build
      - uses: actions/upload-artifact@v2
        with:
          name: MagicCrystal
          path: build/libs/*